# Generated by Django 5.2.1 on 2025-05-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitLog',
            new_name='Visit',
        ),
    ]
