# Generated by Django 5.2.1 on 2025-05-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='stripe_price_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='stripe_product_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
